apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub # This is the name you'll refer to in your services
  namespace: default
spec:
  type: pubsub.rabbitmq # Dapr built-in component for RabbitMQ
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://guest:guest@rabbitmq:5672" # RabbitMQ server URL (assuming it's running locally)
    - name: durable
      value: "true" # Durable queues ensure that messages are not lost
    - name: deleteWhenUnused
      value: "false" # Don't delete queues when they are unused
    - name: lazy
      value: "false" # If true, messages are not put in memory (useful for large queues)
